spring:
  profiles:
    default: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: file:media/,classpath:/static
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:sqlite:db.sqlite
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

logging:
  level:
    root: info
#  config: file:logback-spring.xml

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
